Additional Pokemon form evolutions
Crobat4/pokeclicker pull request #8
Opened 2022-10-27 19:50 UTC by osherwott

Added new by consulting older, replaced commits
* Eiscue (Ice Face) to (No Ice Face) in Fire environments. Also added during Sunny weather
* Cramorant to (Gulping) in Water environments at level 50 and (Gorging) at level 50 but during Thunderstorm weather instead of in PowerPlant environments

Added evolutions between all forms for continuity
* Castform during proper weather
* Burmy during proper environment
* Cherrim (Sunshine) to (Overcast) in all weather but Clear and Windy
* Cramorant under proper conditions
* Eiscue (No Ice Face) to (Ice Face) in Ice environments and Snow, Blizzard, or Hail weather

2022-10-28 13:56 UTC, Crobat4 commented
Cramorant (Gulping) should be rain weather instead environment imo, since that's how it currently is on routes, or both.
Base Cramorant should be all weathers but rain and thunderstorm (like how base Castform is made).
Cherrim (Overcast) should be all weathers but sunny, like the main games.
The rest are fine.

2022-10-28 13:57 UTC, Crobat4 requested changes
Cramorant (Gulping) should be rain weather instead environment imo, since that's how it currently is on routes, or both.
Base Cramorant should be all weathers but rain and thunderstorm (like how base Castform is made).
Cherrim (Overcast) should be all weathers but sunny, like the main games.
The rest are fine.

2022-10-29 02:35 UTC, osherwott commented
Changed as per your suggestion

Ideally I'd like Cramorant's forms to change on water routes depending on the weather, but that's two different conditions that aren't connected by any current evolution method formula. I think restricting Cramorant's forms to water environments would better reflect the games, where it changes forms after using Dive. If you'd be interested in such a formula, I'd be glad to open another PR and try to figure something out, but for the meantime I'm satisfied with weather conditions.

2022-10-29 03:56 UTC, Crobat4 approved these changes
Very nice, thanks for the PR

2022-10-29 03:57 UTC, merged